version: '3.8'

# Main docker-compose file that includes all services
# This uses the include feature to combine all service docker-compose files

include:
  - auth/docker-compose.yml
  - catalogo/docker-compose.yml
  - habilidades/docker-compose.yml
  - plantios/docker-compose.yml
  - tutoriais_tarefas/docker-compose.yml

# Create the shared network that all services use
networks:
  default:
    name: shared-network
