# Generated by Django 5.2.1 on 2025-06-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Ex: 1, 2, 3 (valor numérico)', max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(default='un', help_text='Ex: un, Litros, g', max_length=50, verbose_name='Unidade')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriais_material', to='tutoriais.material', verbose_name='Material')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='tutoriais.tutorial', verbose_name='Tutorial')),
            ],
            options={
                'verbose_name': 'Material do Tutorial',
                'verbose_name_plural': 'Materiais do Tutorial',
                'unique_together': {('tutorial', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(help_text='Ordem da etapa no processo', verbose_name='Ordem')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='tutoriais.tutorial', verbose_name='Tutorial')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['tutorial', 'ordem'],
                'unique_together': {('tutorial', 'ordem')},
            },
        ),
    ]
