# Generated by Django 5.2.1 on 2025-05-13 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nome_cientifico', models.CharField(max_length=150, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('horas_sol', models.CharField(max_length=100)),
                ('solo_ideal', models.CharField(max_length=100)),
                ('ventilacao', models.CharField(max_length=100)),
                ('temperatura_ideal', models.CharField(max_length=100)),
                ('estacao_plantio', models.CharField(max_length=100)),
                ('dias_maturidade', models.IntegerField()),
                ('dificuldade', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.categoria')),
            ],
        ),
    ]
