# Generated by Django 5.2.1 on 2025-06-30 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SugestaoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta_sugerida', models.CharField(max_length=100)),
                ('usuario', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('categoria_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='plantas.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('nome_cientifico', models.CharField(max_length=150, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/')),
                ('horas_sol', models.CharField(max_length=100)),
                ('solo_ideal', models.CharField(max_length=100)),
                ('ventilacao', models.CharField(max_length=100)),
                ('temperatura_minima', models.DecimalField(decimal_places=2, help_text='Temperature in ºC', max_digits=5)),
                ('temperatura_ideal', models.DecimalField(decimal_places=2, help_text='Temperature in ºC', max_digits=5)),
                ('temperatura_maxima', models.DecimalField(decimal_places=2, help_text='Temperature in ºC', max_digits=5)),
                ('estacao_plantio', models.CharField(max_length=100)),
                ('dias_maturidade', models.IntegerField()),
                ('dificuldade', models.DecimalField(decimal_places=1, help_text='Difficulty level from 1 to 5', max_digits=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='plantas.categoria')),
                ('subcategorias', models.ManyToManyField(blank=True, related_name='plantas', to='plantas.subcategoria')),
            ],
        ),
    ]
