# Generated by Django 5.2.1 on 2025-06-25 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilidade.habilidade')),
            ],
            options={
                'unique_together': {('user_id', 'habilidade')},
            },
        ),
    ]
