# Generated by Django 5.2.1 on 2025-07-05 20:58

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('xp', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('nivel', models.IntegerField(default=1)),
                ('xp_para_upar', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('nivel'), '*', models.Value(30)), '-', models.Value(20)), output_field=models.IntegerField())),
                ('porcentagem', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('xp'), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('nivel'), '*', models.Value(30)), '-', models.Value(20))), '*', models.Value(100)), output_field=models.DecimalField(decimal_places=2, max_digits=5))),
                ('habilidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habilidade.habilidade')),
            ],
            options={
                'unique_together': {('user_id', 'habilidade')},
            },
        ),
    ]
