# Generated by Django 5.2.1 on 2025-07-03 14:34

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('xp', models.IntegerField(default=1)),
                ('nivel', models.IntegerField(default=1)),
                ('xp_para_upar', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.Value(10), '*', django.db.models.functions.math.Power(2, django.db.models.expressions.CombinedExpression(models.F('nivel'), '-', models.Value(1)))), output_field=models.IntegerField())),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilidade.habilidade')),
            ],
            options={
                'unique_together': {('user_id', 'habilidade')},
            },
        ),
    ]
