# Generated by Django 5.2.1 on 2025-07-08 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('data_plantio', models.DateField()),
                ('data_prevista_colheita', models.DateField()),
                ('saude', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sede', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('situacao', models.CharField(max_length=100)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
                ('data_atualizacao_saude', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao_sede', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
