# Generated by Django 5.2.1 on 2025-06-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('data_plantio', models.DateField()),
                ('data_prevista_colheita', models.DateField()),
                ('saude', models.FloatField()),
                ('sede', models.FloatField()),
                ('situacao', models.CharField(max_length=100)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
